openapi: 3.0.3
info:
  title: Cadastro de Autor
  description: API para o cadastro de autores na Biblioteca Digital.
  version: 1.0.0

tags:
  - name: Autores
    description: Operações relacionadas a autores
paths:
  /autores:
    post:
      tags:
        - Autores
      summary: Cadastra um novo autor
      description: Cria e armazena um novo autor no sistema.
      operationId: registerAuthor
      requestBody:
        description: Objeto com os dados do autor a ser criado.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutorRequest'
        required: true
      responses:
        '201':
          description: Autor cadastrado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutorResponse'
        '400':
          description: Requisição inválida. O corpo da requisição está malformado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Erro de validação. Os dados enviados são inválidos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Erro inesperado no servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    get:
      tags:
        - Autores
      summary: Lista autores com filtros opcionais
      description: >
        Retorna uma lista de autores cadastrados no sistema.
        A lista pode ser filtrada opcionalmente por país de nacionalidade e/ou por nome.
        Se nenhum filtro for fornecido, todos os autores serão retornados.
      operationId: getAllAuthors
      parameters:
        - name: nacionalityCountry
          in: query
          description: Filtra autores pelo país de nacionalidade. A busca é case-insensitive.
          required: false
          schema:
            type: string
            example: Brasil
        - name: name
          in: query
          description: Filtra autores cujo nome contém o valor fornecido. A busca é case-insensitive.
          required: false
          schema:
            type: string
            example: Maria
      responses:
        '200':
          description: Lista de autores retornada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAutorResponse'
        default:
          description: Erro inesperado no servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /autores/{id}:
    parameters:
      - name: id
        in: path
        description: ID do autor.
        required: true
        schema:
          type: integer
          format: int64
    get:
      tags:
        - Autores
      summary: Retorna um autor específico
      description: Retorna os dados de um autor específico pelo seu ID.
      operationId: getAuthorById
      responses:
        '200':
          description: Autor encontrado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutorResponse'
        '404':
          description: Autor não encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Erro inesperado no servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    put:
      tags:
        - Autores
      summary: Atualiza os dados de um autor cadastrado
      description: Atualiza os dados de um autor cadastrado no sistema.
      operationId: updateAuthor
      requestBody:
        description: Objeto com os dados do autor a ser atualizado.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutorRequest'
      responses:
        '200':
          description: Autor atualizado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutorResponse'
        '404':
          description: Autor não encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Erro de validação. Os dados enviados são inválidos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Erro inesperado no servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      tags:
        - Autores
      summary: Deleta um autor cadastrado
      description: Deleta os dados de um autor cadastrado no sistema.
      operationId: deleteAuthor
      responses:
        '204':
          description: Autor deletado com sucesso.
        '404':
          description: Autor não encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Erro inesperado no servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:

    AutorRequest:
      type: object
      required:
        - name
        - dateBirth
        - nacionalityCountry
      properties:
        name:
          type: string
          description: Nome completo do autor.
          example: "Maria da Silva"
        dateBirth:
          type: string
          format: date
          description: Data de nascimento do autor.
          example: "1980-01-25"
        nacionalityCountry:
          type: string
          description: País de nacionalidade do autor.
          example: "Brasil"

    ListAutorResponse:
      type: array
      items:
        $ref: '#/components/schemas/AutorResponse'

    AutorResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único do autor gerado pelo sistema.
          example: 101
        name:
          type: string
          example: "Maria da Silva"
        dateBirth:
          type: string
          format: date
          example: "1980-01-25"
        nacionalityCountry:
          type: string
          example: "Brasil"

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
