spring:
  application:
    name: Produtos Api
  datasource:
    url: ${URL_DATABASE}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:senha_local_padrao}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  output:
    ansi:
      enabled: ALWAYS

management:
  port: 9090
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: application.log
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

server:
  port: 8080
  servlet:
    context-path: /api/v1
  # CRUCIAL: Faz o Spring respeitar os cabeçalhos X-Forwarded do Nginx
  # Isso garante que os redirecionamentos usem o IP/Porta do cliente (Nginx) e não do container
  forward-headers-strategy: framework

## Perfil de produção
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

## Perfil de homologacao
---
spring:
  config:
    activate:
      on-profile: homologacao
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
