spring:
  application:
    name: Produtos Api
  datasource:
    # Configuração padrão do banco de dados, usando variáveis de ambiente com valores padrão para ambiente local.
    # A URL é construída a partir de partes para maior clareza e flexibilidade.
    # A URL abaixo é um exemplo para desenvolvimento local, incluindo o parâmetro necessário.
    # O valor padrão assume que o MySQL está rodando na porta 6603 do host e o banco se chama 'scad_db'.
    url: ${URL_DATABASE}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:senha_local_padrao}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Dialeto atualizado conforme recomendação do Hibernate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  output:
    ansi:
      enabled: ALWAYS
management:
  port: 9090
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: application.log
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

server:
  port: 8080
  servlet:
    context-path: /api/v1

## Perfil de produção
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

## Perfil de homologacao
---
spring:
  config:
    activate:
      on-profile: homologacao
  # O perfil 'homologacao' herda as configurações de 'datasource' e 'security' do perfil padrão.
  # A única configuração que estamos sobrescrevendo aqui é o comportamento do hibernate.
  jpa:
    show-sql: false
    hibernate:
      # 'update' é útil para desenvolvimento, mas NUNCA deve ser usado em produção.
      ddl-auto: update
