package br.com.scad.scad.service.mapper;

import br.com.scad.scad.domain.Client;
import br.com.scad.scad.dto.ClientRequest;
import br.com.scad.scad.dto.ClientResponse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.oauth2.server.authorization.client.RegisteredClient;

@Mapper(componentModel = "spring")
public interface ClientMapper {
     // Maps the request DTO to the domain entity, encoding the secret.
     @Mapping(target = "clientSecret", expression = "java(passwordEncoder.encode(client.clientSecret()))")
     @Mapping(target = "id", ignore = true) // The ID is generated by the database
     Client toEntity(ClientRequest client, PasswordEncoder passwordEncoder);

     // Maps the domain entity to the response DTO.
     ClientResponse toResponse(Client client);

     ClientRequest toClientRequestMapper(RegisteredClient registeredClient);
}
